name: Build and deploy documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Docker image used for static pages creation
        run: docker build -t intel/cc-docu .
        working-directory: ${{ github.workspace }}

      - name: Create static pages of Intel TDX documentation
        run: docker run --rm -i -v ${PWD}:/docs intel/cc-docu build  --strict
        working-directory: ${{ github.workspace }}

      - name: Upload static pages of documentation as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-documentation-pages
          overwrite: true
          path: site
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download static pages of documentation from artifact
        uses: actions/download-artifact@v4
        with:
          name: static-documentation-pages
          path: site/

      - name: Deploy stable version of documentation to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "./site"
          skip_app_build: "true"
          skip_api_build: "true"
